### ISSUE TITLE
How can I use gisttools to calculate energy contributions to a coordination  

### ISSUE THREAD

**Issue by gkxiao** [liedllab/gisttools#1]
Dear author,

Would you mind showing an example how to calculate dG, dTS and dH contributions to atoms in the pdb file of the benzene example?

Thank you very much,
Gaokeng

**Comment by fwaibl** [comment]
Dear Gaokeng,
thanks for your interest in the gisttools package. Sadly, the benzene example is still very incomplete. I will try to upload some example code tomorrow.
Best regards,
Franz

**Comment by fwaibl** [comment]
I added an example.ipynb file containing some examples of how to use gisttools. For your question, you would need the projection_mean (smoother) or projection_nearest (more detailed, sums up to the corresponding integral) methods.

I will close this issue for now, but please let me know if there are problems with the notebook.

Best regards,
Franz
